[package]
name = "sc-urvy"
version = "0.1.0"
authors = ["sirkibsirkib <christopher.esterhuyse@gmail.com>"]

[dependencies]
magnetic = "2.0.0"
trailing_cell = "0.2.1"
serde = "1.0.27"
serde_derive = "1.0.27"
bincode = "0.9.2"
byteorder = "1.2.1"
crypto-hash = "0.3.0"
bidir-map = "1.0.0"